const demoEvents = [
  {
    title: "ORDA Business Conference",
    date: "2026-06-20",
    time: "10:00",
    category: "conference",
    description: "A business conference for digital platforms, management systems and event operations.",
    agenda: "Opening session, keynote talks, networking, closing panel.",
    organizer: "ORDA",
    location: "Astana, Grand Hall",
    format: "offline",
    meetingUrl: "",
    price: 0,
    currency: "KZT",
    featured: true,
    tags: ["business", "conference", "networking"],
    capacity: 160,
    status: "published",
  },
  {
    title: "Smart Event Technologies Forum",
    date: "2026-06-27",
    time: "11:30",
    category: "forum",
    description: "Forum about web platforms, registration systems, analytics and conference management.",
    agenda: "Technology review, product cases, Q&A session.",
    organizer: "ORDA Academy",
    location: "Almaty, Conference Center A",
    format: "hybrid",
    meetingUrl: "https://meet.google.com/orda-forum",
    price: 5000,
    currency: "KZT",
    featured: true,
    tags: ["technology", "analytics", "hybrid"],
    capacity: 120,
    status: "published",
  },
  {
    title: "Startup Meetup",
    date: "2026-07-05",
    time: "16:00",
    category: "meetup",
    description: "A networking meetup for students, startup teams, mentors and investors.",
    agenda: "Pitch session, mentor meetings, open networking.",
    organizer: "ORDA Community",
    location: "Almaty, Hall B",
    format: "offline",
    meetingUrl: "",
    price: 0,
    currency: "KZT",
    featured: false,
    tags: ["startup", "meetup", "pitch"],
    capacity: 80,
    status: "published",
  },
  {
    title: "Digital Education Seminar",
    date: "2026-07-14",
    time: "14:00",
    category: "seminar",
    description: "A seminar on digital education, student projects and information systems.",
    agenda: "Seminar, project discussion, certificate registration.",
    organizer: "ORDA",
    location: "Shymkent, Academic Hall",
    format: "online",
    meetingUrl: "https://zoom.us/j/123456789",
    price: 0,
    currency: "KZT",
    featured: false,
    tags: ["education", "online", "seminar"],
    capacity: 65,
    status: "published",
  },
];

module.exports = demoEvents;
