const demoEvents = [
  {
    title: "Business Technology Expo 2026",
    date: "2026-05-13",
    endDate: "2026-05-15",
    time: "10:00",
    category: "conference",
    description: "B2B-платформа для облачных технологий, автоматизации, корпоративной инфраструктуры и партнерских решений для бизнеса.",
    agenda: "Expo opening, cloud keynote, vendor sessions, B2B meetings, closing networking",
    organizer: "ORDA Expo Office",
    location: "Atrium Expo Space",
    city: "Астана, Казахстан",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/business-technology-expo",
    price: 0,
    currency: "KZT",
    featured: true,
    tags: ["B2B", "cloud", "expo", "automation"],
    capacity: 620,
    status: "published",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "AI & Innovation Summit 2026",
    date: "2026-06-05",
    time: "10:00",
    category: "conference",
    description: "Саммит о применении искусственного интеллекта, генеративных моделей, автоматизации процессов и инновационных продуктах.",
    agenda: "Opening keynote, AI product tracks, startup showcase, networking",
    organizer: "ORDA",
    location: "Grand Hall A",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/ai-innovation-summit",
    price: 0,
    currency: "KZT",
    featured: true,
    tags: ["AI", "innovation", "digital", "networking"],
    capacity: 420,
    status: "published",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "GO DIGITAL EURASIA 2026",
    date: "2026-07-01",
    endDate: "2026-07-02",
    time: "09:30",
    category: "forum",
    description: "Форум о цифровой трансформации бизнеса, клиентском опыте, данных, автоматизации и переходе компаний к digital-first модели.",
    agenda: "Digital strategy, CX analytics, automation cases, boardroom sessions",
    organizer: "Eurasia Digital Alliance",
    location: "Grand Hall A",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 25000,
    currency: "KZT",
    featured: true,
    tags: ["digital", "transformation", "business"],
    capacity: 390,
    status: "published",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "FinTech Conference Central Asia",
    date: "2026-08-20",
    time: "11:00",
    category: "conference",
    description: "Конференция о платежных системах, open banking, финтех-регулировании, цифровых кошельках и B2B-платформах.",
    agenda: "Regulation briefing, bank panels, product demos, investor meetups",
    organizer: "Central Asia FinTech Hub",
    location: "Silk Road Conference Room",
    city: "Алматы",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/fintech-central-asia",
    price: 30000,
    currency: "KZT",
    featured: false,
    tags: ["fintech", "banking", "payments"],
    capacity: 120,
    status: "published",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Smart Business Forum",
    date: "2026-09-12",
    time: "10:30",
    category: "forum",
    description: "Деловой форум для предпринимателей и управленцев о росте, продажах, операционных системах и smart-управлении.",
    agenda: "CEO talks, operations clinic, sales systems, networking lounge",
    organizer: "Smart Business Club",
    location: "Orion Hall B",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 18000,
    currency: "KZT",
    featured: false,
    tags: ["business", "management", "sales"],
    capacity: 180,
    status: "published",
    image: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Product Community Meetup",
    date: "2026-05-28",
    time: "18:30",
    category: "meetup",
    description: "Вечерняя встреча продуктовых менеджеров, аналитиков и основателей о discovery, метриках и запуске новых функций.",
    agenda: "Lightning talks, Q&A, networking",
    organizer: "PM Society",
    location: "Workshop Hub C",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 0,
    currency: "KZT",
    featured: false,
    tags: ["product", "meetup", "analytics"],
    capacity: 90,
    status: "published",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "HR Leadership Forum",
    date: "2026-06-18",
    time: "11:30",
    category: "forum",
    description: "Форум о people strategy, развитии талантов, вовлеченности команд и операционных HR-процессах.",
    agenda: "Panels, practical cases, round table",
    organizer: "People First",
    location: "Orion Hall B",
    city: "Алматы",
    format: "offline",
    meetingUrl: "",
    price: 15000,
    currency: "KZT",
    featured: false,
    tags: ["HR", "leadership", "culture"],
    capacity: 180,
    status: "published",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Education Seminar: AI in Learning",
    date: "2026-06-26",
    time: "14:00",
    category: "seminar",
    description: "Практический семинар о внедрении AI-инструментов в учебные программы, корпоративное обучение и оценку результатов.",
    agenda: "Opening session, workshop, implementation roadmap",
    organizer: "EdLab",
    location: "Nova Training Lab",
    city: "Астана",
    format: "online",
    meetingUrl: "https://meet.example.com/education-ai",
    price: 5000,
    currency: "KZT",
    featured: false,
    tags: ["education", "AI", "seminar"],
    capacity: 140,
    status: "published",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Cybersecurity Day Kazakhstan",
    date: "2026-10-07",
    time: "09:00",
    category: "briefing",
    description: "Практический день по информационной безопасности: SOC, защита данных, управление рисками и реагирование на инциденты.",
    agenda: "Threat landscape, SOC cases, tabletop exercise, vendor demos",
    organizer: "SecureOps KZ",
    location: "Grand Hall A",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/cyber-day",
    price: 22000,
    currency: "KZT",
    featured: false,
    tags: ["security", "SOC", "risk"],
    capacity: 300,
    status: "published",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Finance Briefing 2026",
    date: "2026-11-19",
    time: "09:30",
    category: "briefing",
    description: "Закрытая сессия о корпоративных финансах, прогнозах рынка, бюджетировании и стратегии на следующий год.",
    agenda: "Market overview, forecasts, executive Q&A",
    organizer: "Fin Board",
    location: "Boardroom D",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/finance-briefing",
    price: 20000,
    currency: "KZT",
    featured: false,
    tags: ["finance", "briefing", "strategy"],
    capacity: 36,
    status: "draft",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
  },
];

module.exports = demoEvents;
