const demoEvents = [
  {
    title: "Business Technology Expo 2026",
    date: "2026-05-13",
    endDate: "2026-05-15",
    time: "10:00",
    category: "conference",
    description: "B2B-платформа для облачных технологий, автоматизации, корпоративной инфраструктуры и партнерских решений для бизнеса.",
    agenda: "Expo opening, cloud keynote, vendor sessions, B2B meetings, closing networking",
    organizer: "ORDA Expo Office",
    location: "Atrium Expo Space",
    city: "Астана, Казахстан",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/business-technology-expo",
    price: 0,
    currency: "KZT",
    featured: true,
    tags: ["B2B", "cloud", "expo", "automation"],
    capacity: 620,
    status: "published",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "AI & Innovation Summit 2026",
    date: "2026-06-05",
    time: "10:00",
    category: "conference",
    description: "Саммит о применении искусственного интеллекта, генеративных моделей, автоматизации процессов и инновационных продуктах.",
    agenda: "Opening keynote, AI product tracks, startup showcase, networking",
    organizer: "ORDA",
    location: "Grand Hall A",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/ai-innovation-summit",
    price: 0,
    currency: "KZT",
    featured: true,
    tags: ["AI", "innovation", "digital", "networking"],
    capacity: 420,
    status: "published",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "GO DIGITAL EURASIA 2026",
    date: "2026-07-01",
    endDate: "2026-07-02",
    time: "09:30",
    category: "forum",
    description: "Форум о цифровой трансформации бизнеса, клиентском опыте, данных, автоматизации и переходе компаний к digital-first модели.",
    agenda: "Digital strategy, CX analytics, automation cases, boardroom sessions",
    organizer: "Eurasia Digital Alliance",
    location: "Grand Hall A",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 25000,
    currency: "KZT",
    featured: true,
    tags: ["digital", "transformation", "business"],
    capacity: 390,
    status: "published",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "FinTech Conference Central Asia",
    date: "2026-08-20",
    time: "11:00",
    category: "conference",
    description: "Конференция о платежных системах, open banking, финтех-регулировании, цифровых кошельках и B2B-платформах.",
    agenda: "Regulation briefing, bank panels, product demos, investor meetups",
    organizer: "Central Asia FinTech Hub",
    location: "Silk Road Conference Room",
    city: "Алматы",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/fintech-central-asia",
    price: 30000,
    currency: "KZT",
    featured: false,
    tags: ["fintech", "banking", "payments"],
    capacity: 120,
    status: "published",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Smart Business Forum",
    date: "2026-09-12",
    time: "10:30",
    category: "forum",
    description: "Деловой форум для предпринимателей и управленцев о росте, продажах, операционных системах и smart-управлении.",
    agenda: "CEO talks, operations clinic, sales systems, networking lounge",
    organizer: "Smart Business Club",
    location: "Orion Hall B",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 18000,
    currency: "KZT",
    featured: false,
    tags: ["business", "management", "sales"],
    capacity: 180,
    status: "published",
    image: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Product Community Meetup",
    date: "2026-05-28",
    time: "18:30",
    category: "meetup",
    description: "Вечерняя встреча продуктовых менеджеров, аналитиков и основателей о discovery, метриках и запуске новых функций.",
    agenda: "Lightning talks, Q&A, networking",
    organizer: "PM Society",
    location: "Workshop Hub C",
    city: "Астана",
    format: "offline",
    meetingUrl: "",
    price: 0,
    currency: "KZT",
    featured: false,
    tags: ["product", "meetup", "analytics"],
    capacity: 90,
    status: "published",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "HR Leadership Forum",
    date: "2026-06-18",
    time: "11:30",
    category: "forum",
    description: "Форум о people strategy, развитии талантов, вовлеченности команд и операционных HR-процессах.",
    agenda: "Panels, practical cases, round table",
    organizer: "People First",
    location: "Orion Hall B",
    city: "Алматы",
    format: "offline",
    meetingUrl: "",
    price: 15000,
    currency: "KZT",
    featured: false,
    tags: ["HR", "leadership", "culture"],
    capacity: 180,
    status: "published",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Education Seminar: AI in Learning",
    date: "2026-06-26",
    time: "14:00",
    category: "seminar",
    description: "Практический семинар о внедрении AI-инструментов в учебные программы, корпоративное обучение и оценку результатов.",
    agenda: "Opening session, workshop, implementation roadmap",
    organizer: "EdLab",
    location: "Nova Training Lab",
    city: "Астана",
    format: "online",
    meetingUrl: "https://meet.example.com/education-ai",
    price: 5000,
    currency: "KZT",
    featured: false,
    tags: ["education", "AI", "seminar"],
    capacity: 140,
    status: "published",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Cybersecurity Day Kazakhstan",
    date: "2026-10-07",
    time: "09:00",
    category: "briefing",
    description: "Практический день по информационной безопасности: SOC, защита данных, управление рисками и реагирование на инциденты.",
    agenda: "Threat landscape, SOC cases, tabletop exercise, vendor demos",
    organizer: "SecureOps KZ",
    location: "Grand Hall A",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/cyber-day",
    price: 22000,
    currency: "KZT",
    featured: false,
    tags: ["security", "SOC", "risk"],
    capacity: 300,
    status: "published",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Finance Briefing 2026",
    date: "2026-11-19",
    time: "09:30",
    category: "briefing",
    description: "Закрытая сессия о корпоративных финансах, прогнозах рынка, бюджетировании и стратегии на следующий год.",
    agenda: "Market overview, forecasts, executive Q&A",
    organizer: "Fin Board",
    location: "Boardroom D",
    city: "Астана",
    format: "hybrid",
    meetingUrl: "https://meet.example.com/finance-briefing",
    price: 20000,
    currency: "KZT",
    featured: false,
    tags: ["finance", "briefing", "strategy"],
    capacity: 36,
    status: "draft",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
  },
];

const eventTranslationsByTitle = {
  "Business Technology Expo 2026": {
    kk: {
      description: "Бұлтты технологиялар, автоматтандыру, корпоративтік инфрақұрылым және бизнеске арналған серіктестік шешімдер туралы B2B-платформа.",
      agenda: "Экспо ашылуы, cloud keynote, жеткізуші сессиялары, B2B кездесулер, қорытынды networking",
      city: "Астана, Қазақстан",
    },
    en: {
      description: "A B2B platform for cloud technology, automation, corporate infrastructure, and partner solutions for business.",
      agenda: "Expo opening, cloud keynote, vendor sessions, B2B meetings, closing networking",
      city: "Astana, Kazakhstan",
    },
  },
  "AI & Innovation Summit 2026": {
    kk: {
      description: "Жасанды интеллект, генеративті модельдер, процестерді автоматтандыру және инновациялық өнімдер туралы саммит.",
      agenda: "Ашылу keynote, AI өнім тректері, startup showcase, networking",
      city: "Астана",
    },
    en: {
      description: "A summit on artificial intelligence, generative models, process automation, and innovative products.",
      agenda: "Opening keynote, AI product tracks, startup showcase, networking",
      city: "Astana",
    },
  },
  "GO DIGITAL EURASIA 2026": {
    kk: {
      description: "Бизнестің цифрлық трансформациясы, клиент тәжірибесі, деректер, автоматтандыру және digital-first моделіне көшу туралы форум.",
      agenda: "Цифрлық стратегия, CX аналитикасы, автоматтандыру кейстері, boardroom сессиялары",
      city: "Астана",
    },
    en: {
      description: "A forum on business digital transformation, customer experience, data, automation, and the shift to a digital-first model.",
      agenda: "Digital strategy, CX analytics, automation cases, boardroom sessions",
      city: "Astana",
    },
  },
  "FinTech Conference Central Asia": {
    kk: {
      description: "Төлем жүйелері, open banking, финтех реттеу, цифрлық әмияндар және B2B-платформалар туралы конференция.",
      agenda: "Реттеу briefing, банк панельдері, product demos, investor meetups",
      city: "Алматы",
    },
    en: {
      description: "A conference on payment systems, open banking, fintech regulation, digital wallets, and B2B platforms.",
      agenda: "Regulation briefing, bank panels, product demos, investor meetups",
      city: "Almaty",
    },
  },
  "Smart Business Forum": {
    kk: {
      description: "Кәсіпкерлер мен басқарушыларға арналған өсу, сатылым, операциялық жүйелер және smart-басқару туралы іскерлік форум.",
      agenda: "CEO talks, operations clinic, sales systems, networking lounge",
      city: "Астана",
    },
    en: {
      description: "A business forum for entrepreneurs and managers about growth, sales, operating systems, and smart management.",
      agenda: "CEO talks, operations clinic, sales systems, networking lounge",
      city: "Astana",
    },
  },
  "Product Community Meetup": {
    kk: {
      description: "Product менеджерлер, аналитиктер және негізін қалаушылар үшін discovery, метрикалар және жаңа функцияларды іске қосу туралы кешкі кездесу.",
      agenda: "Lightning talks, Q&A, networking",
      city: "Астана",
    },
    en: {
      description: "An evening meetup for product managers, analysts, and founders about discovery, metrics, and launching new features.",
      agenda: "Lightning talks, Q&A, networking",
      city: "Astana",
    },
  },
  "HR Leadership Forum": {
    kk: {
      description: "People strategy, таланттарды дамыту, командалардың қатысуы және операциялық HR-процестер туралы форум.",
      agenda: "Панельдер, практикалық кейстер, дөңгелек үстел",
      city: "Алматы",
    },
    en: {
      description: "A forum on people strategy, talent development, team engagement, and operational HR processes.",
      agenda: "Panels, practical cases, round table",
      city: "Almaty",
    },
  },
  "Education Seminar: AI in Learning": {
    kk: {
      description: "AI-құралдарын оқу бағдарламаларына, корпоративтік оқытуға және нәтижені бағалауға енгізу туралы практикалық семинар.",
      agenda: "Ашылу сессиясы, workshop, енгізу roadmap",
      city: "Астана",
    },
    en: {
      description: "A practical seminar on implementing AI tools in curricula, corporate learning, and outcome assessment.",
      agenda: "Opening session, workshop, implementation roadmap",
      city: "Astana",
    },
  },
  "Cybersecurity Day Kazakhstan": {
    kk: {
      description: "Ақпараттық қауіпсіздік бойынша практикалық күн: SOC, деректерді қорғау, тәуекелдерді басқару және инциденттерге әрекет ету.",
      agenda: "Threat landscape, SOC кейстері, tabletop exercise, vendor demos",
      city: "Астана",
    },
    en: {
      description: "A practical day on cybersecurity: SOC, data protection, risk management, and incident response.",
      agenda: "Threat landscape, SOC cases, tabletop exercise, vendor demos",
      city: "Astana",
    },
  },
  "Finance Briefing 2026": {
    kk: {
      description: "Корпоративтік қаржы, нарық болжамдары, бюджеттеу және келесі жыл стратегиясы туралы жабық сессия.",
      agenda: "Нарық шолуы, болжамдар, executive Q&A",
      city: "Астана",
    },
    en: {
      description: "A private session on corporate finance, market forecasts, budgeting, and next-year strategy.",
      agenda: "Market overview, forecasts, executive Q&A",
      city: "Astana",
    },
  },
};

demoEvents.forEach((event) => {
  const extra = eventTranslationsByTitle[event.title] || {};
  event.translations = {
    ru: {
      title: event.title,
      description: event.description,
      agenda: event.agenda,
      organizer: event.organizer,
      location: event.location,
      city: event.city,
    },
    kk: {
      title: event.title,
      organizer: event.organizer,
      location: event.location,
      ...(extra.kk || {}),
    },
    en: {
      title: event.title,
      organizer: event.organizer,
      location: event.location,
      ...(extra.en || {}),
    },
  };
});

module.exports = demoEvents;
